name: Integration tests

on: [push]

jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.19.0
        env:
          CI: true
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
          working-directory: packages/reason-relay/reason-relay-ppx
      - name: Build PPX
        uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
          working-directory: packages/reason-relay/reason-relay-ppx
      - name: Build ReasonRelayBin
        uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
          working-directory: packages/reason-relay-bin
      - name: Copy built ReasonRelayBin file
        working-directory: packages/reason-relay-bin
        run: |
          ./copyIntoPlace.sh
      - name: Install - language plugin
        working-directory: packages/reason-relay/language-plugin
        run: |
          yarn --frozen-lockfile
      - name: Build - language plugin
        working-directory: packages/reason-relay/language-plugin
        run: |
          yarn build
      - name: Install - bindings
        working-directory: packages/reason-relay
        run: |
          yarn install
      - name: Build - Relay test files
        working-directory: packages/reason-relay
        run: |
          yarn build:test
      - name: git status
        id: git_status
        run: |
          echo "::set-output name=status::$( git status --porcelain )"
      - name: Exit if files modified
        run: |
          exit 1
        if: steps.git_status.outputs.status
      - name: Build - bindings
        working-directory: packages/reason-relay
        run: |
          yarn build
      - name: Integration tests
        working-directory: packages/reason-relay
        run: |
          yarn test:ci
