name: Language plugin

on: [push]

jobs:
  test:
    name: Language plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/reason-relay/language-plugin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.19.0
        env:
          CI: true
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Install esy
        run: npm install -g esy
      - name: Build ReasonRelayBin
        uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
          working-directory: packages/reason-relay-bin
      - name: Copy built ReasonRelayBin file
        working-directory: packages/reason-relay-bin
        run: |
          ./copyIntoPlace.sh
      - name: Test
        run: |
          yarn test:ci
